name: todo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.2
  freezed: ^2.5.2

  bloc: ^8.1.4
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  dio: ^5.5.0
  intl: ^0.20.2
  auto_route: 10.0.1
  get_it: ^7.7.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: SFProTextSemiBold
      fonts:
        - asset: assets/fonts/SFProText-Semibold.ttf
    - family: SFProTextRegular
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
    - family: SFProTextMedium
      fonts:
        - asset: assets/fonts/SFProText-Medium.ttf